blog/urls.py
# -*- coding:utf-8 -*-
#  made in ly
from django.conf.urls import url
from .import views

app_name = 'blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name="index"),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^in_time/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.In_TimeView.as_view(), name="in_time"),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^tag_cloud/(?P<pk>[0-9]+)/$', views.Tag_CloudView.as_view(), name='tag_cloud'),
#    url(r'^to_author/(?P<author>[0-9]+)/$',views.To_authorView.as_view(), name = 'to_author'),

]

comments/urls.py
# -*- coding:utf-8 -*-
#  made in ly
from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^post_comment/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/models.py
#coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.


#python_2_unicode_compatible 装饰器用于兼容python2
#分类
@python_2_unicode_compatible
class Category(models.Model):

    '''
        Django 要求模型必须继承models.Model类。
        Django 内置的全部类型可查看文档：
        https: // docs.djangoproject.com / en / 1.10 / ref / models / fields / # field-types
    '''
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


#标签
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


#文章
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()


    #下去试试 models.TimeField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField()

    #摘要，允许空值
    excerpt = models.CharField(max_length=200, blank=True)

    views = models.PositiveIntegerField(default=0)


    '''
    这里的分类与标签，和上面定义过的不一样，这里是把文章对应的分类与标签对应关联起来
    规定：①一篇文章只能有一个分类，但是一个分类中可以有多篇文章，用外键关联
         ②一篇文章可以用多个标签，一个标签下也可以有多篇文章，用ManyToManyField()关联
         ③文章可以没有标签
    '''
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs = {'pk': self.pk})

    class Meta:
        ordering = ["-created_time"]

    def increase_views(self):
        self.views +=1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])


            #先将markdown文本渲染成HTML文本，然后用strip_tags去掉HTML文本的全部HTML标签（为了防止文本中含有标签弄坏排版）
            #抽取前60个字符给excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:60]

        #调用父类的save方法将数据保存到数据库中
        super(Post,self).save(*args, **kwargs)

comments/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
# Create your models here.

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

    class Meta:
        ordering = ["-created_time"]

blog/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404
import markdown
# Create your views here.
from comments.forms import CommentForm
from django.http import HttpResponse
from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q


class IndexView(ListView):
    # 将model指定为Post，告诉Django我要获取的是Post
    model = Post
    # 指定这个视图渲染的模板
    template_name = 'blog/index.html'
    # 指定获取的模型列表数据保存的变量名，这个变量会被传递给模板
    context_object_name = 'post_list'
    paginate_by = 3


    def get_context_data(self, **kwargs):
        # 覆写该方法，以便我们获得自定义的模板变量

        context = super(IndexView,self).get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []
        right = []

        left_has_more = False
        right_has_more = False
        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages

        #获得整个分页的页码列表
        page_range = list(paginator.page_range)

        if page_number ==1:
#            right = page_range[page_number:page_number + 1]
            right = page_range[page_number:page_number + 1]

            if right[-1] < total_pages -1:
                right_has_more = True

            if right[-1] <total_pages:
                last = True
        elif page_number ==total_pages:
            left = page_range[(page_number - 3) if (page_number -3) > 0 else 0 :page_number -1]

            if left[0] > 2:
                left_has_more =True
            if left[0] >1:
                first = True

        else:
            left = page_range[(page_number - 3) if(page_number-3) >0 else 0: page_number -1]
            right = page_range[page_number:page_number + 1]

            if right[-1] < total_pages -1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            if left[0] >2:
                left_has_more = True
            if left[0] >1:
                first = True


        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'last':last,
            'first': first,
        }

        return data


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆盖父类get方法
        # 父类get方法返回一个Httpresponse实例，
        # 之所以调用父类get方法，是因为只有当get方法被调用后，才有self.object属性，其值为Post模型实例
        response = super(PostDetailView,self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        # 覆盖父类get_object方法

        post = super(PostDetailView,self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            #   'markdown.extensions.toc',
            TocExtension(slugify=slugify),
            ])


        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆盖get_context_data 的目的是为了除了将post传递给模板外（DateilView已经帮我们完成）
        # 还要把评论表单、post下评论的列表传递给模板
        context = super(PostDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update(
            {
                'form':form,
                'comment_list':comment_list
            }
        )
        return context


class In_TimeView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(In_TimeView,self).get_queryset().filter(created_time__year=year, created_time__month=month)

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class Tag_CloudView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tg = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(Tag_CloudView, self).get_queryset().filter(tags=tg)



def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键词"
        return render(request,'blog/index.html',{'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list })

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>

    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">url：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <ul class="comment-list list-unstyled">
                <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>

{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list%}
        <article class="post post-{{ post.pk }}">
            <header>
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
                </h1>
                <div>
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="post-date"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} 评论 </a> </span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}。。。</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">详细内容 <span class="meta-nav"> → </span></a>
                </div>
            </div>
        </article>
    {% empty %}
        {{ post_list }}
        <div class="on-post">
            这里暂时还没有发布文章！
        </div>
    {% endfor %}


    {% if is_paginated %}
        <div class="pagination">
        {% if first %}
            <a href="?page=1">1</a>
        {% endif %}

        {% if left %}
            {% if left_has_more %}
                <span>...</span>
            {% endif %}
            {% for i in left %}
                <a href="?page={{ i }}"> {{ i }} </a>
            {% endfor %}
        {% endif %}

        <a href="?page={{ page_obj.number }}" style="color: #aa0000">{{ page_obj.number }}</a>

        {% if right %}
            {% for i in right %}
                <a href="?page={{ i }}"> {{ i }} </a>
            {% endfor %}
            {% if right_has_more %}
                <span>...</span>
            {% endif %}
        {% endif %}

        {% if last %}
            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }} </a>
        {% endif %}
        </div>
    {% endif %}


{% endblock main %}

templates/blog/备份 index.html
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% for post in post_list%}
                    <article class="post post-{{ post.pk }}">
                        <header>
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
                            </h1>
                            <div>
                                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date" datatime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                                <span class="comments-link"><a href="#">4 评论</a></span>
                                <span class="views-count"><a href="#">123 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">详细内容 <span class="meta-nav"> → </span></a>
                            </div>
                        </div>

                    </article>
                {% empty %}
                    <div class="on-post">
                        暂时还没有发布文章！
                    </div>
                {% endfor %}

                <!--
                <article class="post post-1">
                    <header class="bentry-header">
                        <h1 class="entry-title">
                            <a href="single.html">Django 博客开发入门教程：前言</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">追梦人物</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
                            开发的技巧...</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                -->
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>